name: Pull Request Build

on:
  pull_request:

jobs:
  call-dapper-build:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: ${{ github.ref_name }}-head
      push: false
    secrets: inherit
